#!/usr/bin/env python3
import os.path
import sys
import gi
gi.require_version('Gtk', '4.0')
gi.require_version('Adw', '1')
from gi.repository import Gtk, Adw, Gdk
from pathlib import Path

css_provider = Gtk.CssProvider()
css_provider.load_from_path('main.css')
Gtk.StyleContext.add_provider_for_display(Gdk.Display.get_default(), css_provider, Gtk.STYLE_PROVIDER_PRIORITY_APPLICATION)


# Prevent app from autostarting again
lockfile_path: str = str(Path.home()) + '/.config/.arkane-welcome.lock'

# TODO: Right now is hard coded to .config, if none-default config dir is used will break
# TODO: Instead use xdg_base_dirs? I opted not to, as to avoid another dependency for this minor feature
if not os.path.isfile(lockfile_path):
    try:
        lockfile = open(lockfile_path, 'x')
    except:
        sys.stderr.write('Failed to create lockfile\n')
else:
    sys.stderr.write('Lockfile already exists\n')


class MainWindow(Gtk.ApplicationWindow):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        # TODO: Open window centered on screen
        # TODO: Decide if app should install Flatpaks or if separate background service should
        # TODO: Ctrl + Q close shortcut

        # Set window properties
        self.set_title("Welcome")

        # Define headerbar
        self.headerbar = Gtk.HeaderBar()

        self.set_titlebar(self.headerbar)

        # Define main
        self.main = Gtk.CenterBox()
        self.set_child(self.main)

        # Set up content box
        self.content_box = Gtk.Box(orientation=Gtk.Orientation.VERTICAL)
        self.main.set_center_widget(self.content_box)

        # Define logo image
        self.logo = Gtk.Image.new_from_file('arkane-logo.webp')
        self.logo.set_pixel_size(128)
        self.logo.set_css_classes(['logo-image'])

        # Define text
        self.welcome_text = Gtk.Label.new("Welcome to Arkane Linux")
        self.welcome_text.set_css_classes(['welcome-text'])

        self.flatpak_text = Gtk.Label.new("Hit the button below to install a collection of default flatpak apps.")
        self.flatpak_text.set_css_classes(['flatpak-text'])

        # Define lower centerbox
        self.button_centerbox = Gtk.CenterBox()

        # Define Flatpak install button
        self.flatpak_button = Gtk.Button(label="Install")
        self.flatpak_button.set_css_classes(['install-flatpaks'])

        # Assemble content
        self.content_box.append(self.logo)
        self.content_box.append(self.welcome_text)
        self.content_box.append(self.flatpak_text)
        self.content_box.append(self.button_centerbox)
        self.button_centerbox.set_center_widget(self.flatpak_button)


class MyApp(Adw.Application):
    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        self.connect('activate', self.on_activate)

    def on_activate(self, app):
        self.win = MainWindow(application=app)
        self.win.set_default_size(600, 375)
        self.win.present()

app = MyApp(application_id="com.example.GtkApplication")
app.run(sys.argv)